logging:
  level:
    com.example.project1: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_test
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      # leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
  jmx:
    enabled: false
  thymeleaf:
    cache: false

server:
  port: 8181