# SQLログ出力
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.EnumType: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_dev
    username: root
    password: password
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      # leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
  jmx:
    enabled: false
  jpa:
    show-sql: true
  thymeleaf:
    cache: false

server:
  port: 8181