name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Refactoring candidate - GitHub action service?
      - name: Set up Docker Compose
        run: |
          docker-compose -f docker/main.yml up -d
      - name: Wait Database
        run: docker-compose -f docker/main.yml run wait db:3306 -- echo "mysql.server is up"
      # TODO change schema to example_test
      - name: Flyway migration
        run: ./gradlew :migration:migrateDev
      - name: Build with Gradle
        run: ./gradlew build --stacktrace