name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        # redisが起動するまで待つヘルスチェックの設定
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: example_test
          TZ: "Asia/Tokyo"
        ports:
          - 3306:3306
        options: >-
            --health-cmd "mysqladmin ping -h 127.0.0.1"
            --health-interval 20s
            --health-timeout 10s
            --health-retries 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Flyway migration
        run: ./gradlew :migration:migrateTest
      - name: Gradle Version
        run: ./gradlew build --version
      - name: Build with Gradle
        run: ./gradlew  --stacktrace